router_settings:
  routing_strategy: simple-shuffle
  
litellm_settings:
  drop_params: True
  telemetry: False
general_settings:
  master_key: sk-1234
  store_model_in_db: true
  store_prompts_in_spend_logs: true